### ISSUE TITLE
Refactor: convert to Sass

### ISSUE THREAD

**Issue by BentleyDavis** [SettleIt/ReasonRoot#9]

**Comment by EdgarOPG** [comment]
Greetings, I can't create a new branch, I guess it's caused by the changes on the repo security, can you create a branch called 'convert-css-to-sass'?
until we resolve this issue.

![error](https://user-images.githubusercontent.com/12171078/27019474-10793806-4ef6-11e7-84fe-89ff9ac2a692.png)

Normally on the text input placeholder it's written 'find or create a branch...', but now this input only allows me to filter branches by their name.

**Comment by BentleyDavis** [comment]
I just created the new branch. I believe the property process would be to clone the dev branch to your computer then create a local branch then you can create a pull request from the local branch and that will create a branch on GitHub.

**Comment by rrgarciach** [comment]
Yes, you are right @BentleyDavis. That's the right process and I also would like to enforce to set as a branch naming convention the name pattern:

feature\[issue number]-[issue keywords]

that may look like this:

`feature\9-convert-css-to-sass`

@EdgarOPG in order to create a new branch to work on do as follows:

1. Checkout to `dev` branch and update it by running `git pull origin dev`
2. Create new branch with `git checkout -b feature/9-convert-css-to-sass`
3. Push to origin in order to create that new branch on remote repo: `git push origin feature/9-convert-css-to-sass`

**Comment by EdgarOPG** [comment]
Yeah, sorry I let myself go by this difference, and I did not try use a command in console.

**Comment by BentleyDavis** [comment]
@rrgarciach I like the naming conventions. can you use a slash in a name? I'm not sure we need the label "feature" just the number and the issue keywords. Do we want to zero pad the number so they will sort properly if we ever download them? not a big deal, just a though. I like your process though so do what you think is best here.

@EdgarOPG I appreciate your honesty and willingness to learn.

**Comment by rrgarciach** [comment]
Yes, you can use hyphens and dashes; the only thing to notice here is that some git UI clients breaks the names as if they were directories when you use slashes. 

The idea of using the prefix of "feature" or "bugfix" is to be able to differ the nature or type of each branch and/or its pull request. Maybe we need to give priority to a bug fix rather than features... who knows.

I agree with you regarding the zero leading... maybe a two zero leading indeed (i.e. 001). Is very common to come over more than 99 on projects of this type.
